callbacks:
  speed_monitor:
train_dataset:
  streaming_imagenet1k: # Configuration for ImageNet training data
    split: train
    shuffle: true
    drop_last: true
val_dataset:
  streaming_imagenet1k: # Configuration for ImageNet validation data
    split: val
    shuffle: false
    drop_last: false  
optimizers:
  decoupled_sgdw:
    lr: 2.048
    momentum: 0.875
    weight_decay: 5.0e-4
    dampening: 0
    nesterov: false
schedulers: {}
  #- cosine_decay_with_warmup:
  #    t_warmup: "8ep"
model:
  resnet:
    model_name: resnet50
    initializers:
      - kaiming_normal
      - bn_uniform
    num_classes: 1000
max_duration: 5ep
eval_interval: 1ep
train_batch_size: 128
eval_batch_size: 64
seed: 17
device:
  tpu: {}
dataloader:
  num_workers: 8
precision: bf16
