run_name: test
train_dataset:
  cifar10:
    datadir: /mnt//CIFAR10
    is_train: true
    download: true
    shuffle: true
    drop_last: true
    use_synthetic: true
val_dataset:
  cifar10:
    datadir: /mnt/CIFAR10
    is_train: false
    download: true
    shuffle: false
    drop_last: false
    use_synthetic: true
optimizers:
  decoupled_sgdw:
    lr: 1.2
    momentum: 0.9
    weight_decay: 2.0e-3
schedulers: {}
model:
  resnet_cifar:
    model_name: resnet_56
    initializers:
      - kaiming_normal
      - bn_uniform
max_duration: 5ep
train_batch_size: 128
eval_batch_size: 128
seed: 17
grad_accum: 1
dataloader:
  num_workers: 8
precision: fp32
device:
  tpu: {}