run_name: resnet50-methods
model:
  resnet:
    model_name: resnet50
    loss_name: binary_cross_entropy_with_logits
    initializers:
      - kaiming_normal
      - bn_uniform
      - linear_log_constant_bias
    num_classes: 1000
algorithms:
  - blurpool: {}
  - channels_last: {}
  - label_smoothing:
      smoothing: 0.08
  - progressive_resizing:
      size_increment: 4
      delay_fraction: 0.4
  - ema:
      update_interval: 20ba
callbacks:
  speed_monitor:
train_dataset:
  imagenet:
    datadir: /tmp/ILSVRC/Data/CLS-LOC/
    resize_size: -1
    crop_size: 176 
    is_train: true
    shuffle: true
    drop_last: true
    use_ffcv: false
val_dataset:
  imagenet:
    datadir: /tmp/ILSVRC/Data/CLS-LOC/
    resize_size: 232
    crop_size: 224
    is_train: false
    shuffle: false
    drop_last: false
    use_ffcv: false 
optimizer:
  decoupled_sgdw:
    lr: 2.048
    momentum: 0.875
    weight_decay: 5.0e-4
    dampening: 0
    nesterov: false
scale_schedule_ratio: 0.32
schedulers:
  - cosine_decay_with_warmup:
      t_warmup: "8ep"
max_duration: 90ep
train_batch_size: 2048
eval_batch_size: 2048
eval_interval: 3
seed: 17
device:
  gpu: {}
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
grad_accum: 1
precision: amp