model:
  resnet:
    model_name: resnet50
    loss_name: binary_cross_entropy_with_logits
    initializers:
      - kaiming_normal
      - bn_uniform
      - linear_log_constant_bias
    num_classes: 1000
callbacks:
  speed_monitor:
train_dataset:
  streaming_imagenet1k: # Configuration for ImageNet training data
    split: train
    shuffle: true
    drop_last: true
val_dataset:
  streaming_imagenet1k: # Configuration for ImageNet validation data
    split: val
    shuffle: false
    drop_last: false
optimizers:
  decoupled_sgdw:
    lr: 2.048
    momentum: 0.875
    weight_decay: 5.0e-4
    dampening: 0
    nesterov: false
schedulers:
  - cosine_decay_with_warmup:
      t_warmup: "8ep"
max_duration: 10ep
train_batch_size: 2048
eval_batch_size: 2048
eval_interval: 3
seed: 17
device:
  amd_gpu: {}
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
grad_accum: 1
precision: amp